pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    #first argument is an empty string which matches the base url
    #the second argument specifies the function name to call in views.py
    #third argumen provides the name 'index' for this URL pattern to refer to later
    path('',views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    path('new_pizza/', views.new_pizza, name='new_pizza'),
    path('new_topping/<int:pizza_id>/', views.new_topping, name='new_topping'),
    path('edit_topping/<int:topping_id>/', views.edit_topping, name='edit_topping'),
    path('new_comment/<int:pizza_id>/', views.new_comment, name='new_comment'),

]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pizzas.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from . import views

app_name='users'

urlpatterns= [
    path('',include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]
    

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)

    date=models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza=models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name=models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms

from . models import Comment, Pizza, Topping

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name']
        labels = {'name':''}

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['name']
        labels = {'name':''}

#REPEAT SLIDE 2 ON PART V FOR COMMENTS

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name']
        labels = {'name':''}

pizzas/views.py
from django.shortcuts import render, redirect
from .forms import PizzaForm, ToppingForm, CommentForm
from . models import Pizza, Topping, Comment
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    #The home page for the pizzeria
    return render(request, 'pizzas/index.html')

#@login_required
def pizzas(request):
    pizzas = Pizza.objects.filter(owner=request.user).order_by('date')
    context = {'pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html',context)


#@login_required
def pizza(request, pizza_id):
    pizza=Pizza.objects.get(id=pizza_id)
    
    toppings = pizza.topping_set.order_by('-date_added') #descending order
    comments = pizza.comment_set.order_by('-date_added')

    context = {'pizza': pizza, 'toppings': toppings, 'comments': comments}
    return render(request, 'pizzas/pizza.html', context)


def new_pizza(request):
    if request.method != 'POST':
        form = PizzaForm()
    else:
        form = PizzaForm(data=request.POST)

        if form.is_valid():
            new_pizza = form.save(commit=False)
            new_pizza.owner = request.user
            new_pizza.save()
            return redirect('pizzas:pizzas')

    context = {'form':form}
    return render(request, 'pizzas/new_pizza.html', context)
#@login_required
def new_topping(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = ToppingForm()
    else:
        form = ToppingForm(data=request.POST)

        if form.is_valid():

            new_topping = form.save(commit=False)
            new_topping.pizza = pizza
            new_topping.owner = request.user
            new_topping.save()
            form.save()
            return redirect('pizzas:pizza', pizza_id = pizza_id)
    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/new_topping.html', context)


#@login_required
def edit_topping(request, topping_id):
    topping = Topping.objects.get(id=topping_id)
    pizza = topping.pizza

    if pizza.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #this argument tells Django to create the form prefilled
        #with this info from the existing topping object
        form = ToppingForm(instance=topping)
    else:
        #POST data submitted, processing data
        form = ToppingForm(instance=topping,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('pizzas:pizza', pizza_id=pizza.id)

    context = {'topping':topping,'pizza':pizza,'form':form}
    return render(request, 'pizzas/edit_topping.html',context)

#@login_required
def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.owner = request.user
            new_comment.save()
            form.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/new_comment.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def register(request):
    #Register a new user
    if request.method != 'POST':
        #Displays the blank registration form
        form = UserCreationForm()
    else:
        #Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            #Save method returns the newly created user object
            new_user = form.save()
            login(request,new_user)
            return redirect('pizzas:index')
    context={'form':form}
    return render(request, 'registration/register.html',context)

pizzas/templates/pizzas/base.html
{% load bootstrap4 %} 

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Christopher's Pizzeria</title>

    {% bootstrap_css %} 
    {% bootstrap_javascript jquery='full' %} 

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'pizzas:index' %}">Christopher's Pizzeria</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
    data-target="#navbarCollapse" aria-controls="navbarCollapse"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pizzas:pizzas' %}">Pizzas</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %} 
                <li class="nav-item">
                    <span class="navbar-text"}">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
            {% else %} 
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
            {% endif %} 
        </ul>
        </div>

        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %} 
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
    </main>
</body>
</html>

pizzas/templates/pizzas/edit_topping.html
{% extends "pizzas/base.html" %} 

{% block content %} 

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p>Edit the pizza's toppings</p>

<form action="{% url 'pizzas:edit_topping' pizza.id %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %} 

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %} 

{% block page_header %} 
<div class="jumbotron">
    <h1 class="display-3">Create and order your own pizza here!</h1>
    <p class="lead">Step 1: Select your pizza style and add toppings.
        <br>
        Step 2: Leave a comment!
    </p>
</div> 
<P>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Click here to join rewards club! &raquo;</a>
        <img src="https://pngimg.com/uploads/pizza/pizza_PNG7142.png" alt="Pizza">
</P>
{% endblock page_header %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %} 
{% block content %} 

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>
<p>Add a comment reviewing this:</p>
<form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }} 

    <button name="submit">Add comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/new_pizza.html
{% extends "pizzas/base.html" %} 

{% block content %} 
<p>Add a new pizza!</p>

<form action="{% url 'pizzas:new_pizza' %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }} 

    <button name="submit">Add a pizza</button>
</form>

{% endblock content %} 

pizzas/templates/pizzas/new_topping.html
{% extends "pizzas/base.html" %} 
{% block content %} 

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>
<p>Add a new topping:</p>

<form action="{% url 'pizzas:new_topping' pizza.id %}" method='post'>
    {% csrf_token %} 
    {{ form.as_p }} 

    <button name="submit">Add Topping</button>


</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %} 

{% block page_header %} 

<h3>{{ pizza }}</h3>
{% endblock page_header %} 
{% block content %} 

<p>Pizza: {{ pizza.name }}</p>

<ul>
    {% for topping in toppings %} 
    <li>
        <p>{{ topping.name|linebreaks }}</p>
        <p>
            <a href="{% url 'pizzas:edit_topping' topping.id %}">Edit topping</a>
        </p>

    </li>
    {% empty %} 
    <li>No toppings for this pizza have been added yet.</li>
    {% endfor %} 
</ul>
<p>
    <a href="{% url 'pizzas:new_topping' pizza.id %}">Add a new topping</a>
</p>
<ul>
    {% for comment in comments %} 
    <li>
        <p> {{ comment.name|linebreaks }}</p>
    </li>
    {% empty %} 
    <li>No comments for this pizza have been written yet.</li>
    {% endfor %} 
</li>
</ul>
    <p>
    <a href="{% url 'pizzas:new_comment' pizza.id %}">Add a new comment</a>
</p>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %} 

{% block page_header %} 

<h1>Pizzas</h1>

{% endblock page_header %} 

{% block content %} 
<ul>
    {% for pizza in pizzas %} 
    <li><h3>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    </h3></li>
    {% empty %} 
    <li><h3>No pizzas have been added yet.</h3></li>
    {% endfor %} 


</ul>

<h3><a href="{% url 'pizzas:new_pizza' %}">Add a new pizza</a></h3>
<P>
    <img src="https://pngimg.com/uploads/pizza/pizza_PNG7142.png" alt="Pizza">
</P>

{% endblock content %}